USE [master]
GO
DECLARE @stmt VARCHAR(900)
IF DB_ID(N'SalesWP') IS NOT NULL
BEGIN
	EXEC('DROP DATABASE [SalesWP]')
	IF @@ERROR <> 0
		PRINT '<<< FAILED DROPPING DATABASE SalesWP >>>'
	ELSE
		PRINT '<<< DROPPED DATABASE SalesWP >>>'
END
GO
CREATE DATABASE [SalesWP]
IF @@ERROR <> 0
	PRINT '<<< FAILED CREATING DATABASE SalesWP >>>'
ELSE
	PRINT '<<< CREATED DATABASE SalesWP >>>'
GO
IF NOT EXISTS(SELECT name FROM [master].[sys].[syslogins] WHERE name = 'Prg_FWP')
BEGIN
	CREATE LOGIN [Prg_FWP] WITH PASSWORD = N'og#yREKL04&!5&', DEFAULT_DATABASE = [SalesWP], CHECK_EXPIRATION = OFF, CHECK_POLICY = ON
	IF @@ERROR <> 0
		PRINT '<<< FAILED CREATING LOGIN Prg_FWP >>>'
	ELSE
		PRINT '<<< CREATED LOGIN Prg_FWP >>>'
END
ELSE
BEGIN
	ALTER LOGIN [Prg_FWP] WITH DEFAULT_DATABASE = [SalesWP]
	IF @@ERROR <> 0
		PRINT '<<< FAILED SETTING DEFAULT DATABASE FOR Prg_FWP >>>'
	ELSE
		PRINT '<<< SET DEFAULT DATABASE FOR Prg_FWP >>>'
END
GO
-- Creating Default DBA login and user
IF NOT EXISTS(SELECT name FROM [master].[sys].[syslogins] WHERE name = 'Admin01')
BEGIN
	CREATE LOGIN [Admin01] WITH PASSWORD = N'TdxLWvm3f$1Y?3HmgG', DEFAULT_DATABASE = [SalesWP], CHECK_EXPIRATION = OFF, CHECK_POLICY = ON
	IF @@ERROR <> 0
		PRINT '<<< FAILED CREATING LOGIN Admin01 >>>'
	ELSE
		PRINT '<<< CREATED LOGIN Admin01 >>>'
END
ELSE
BEGIN
	ALTER LOGIN [Admin01] WITH DEFAULT_DATABASE = [SalesWP]
	IF @@ERROR <> 0
		PRINT '<<< FAILED SETTING DEFAULT DATABASE FOR Admin01 >>>'
	ELSE
		PRINT '<<< SET DEFAULT DATABASE FOR Admin01 >>>'
END
GO
-- Create users in master for new logins
IF NOT EXISTS(SELECT [name] FROM [master].[sys].[database_principals] WHERE [type] = N'S' AND [name] = N'Prg_FWP')
BEGIN
	CREATE USER [Prg_FWP] FOR LOGIN [Prg_FWP]
	IF @@ERROR <> 0
		PRINT '<<< FAILED CREATING USER FOR LOGIN Prg_FWP >>>'
	ELSE
		PRINT '<<< CREATED USER FOR LOGIN Prg_FWP >>>'
END
ELSE
BEGIN
	ALTER USER [Prg_FWP] WITH LOGIN = [Prg_FWP]
	IF @@ERROR <> 0
		PRINT '<<< FAILED ALTER LOGIN FOR USER Prg_FWP >>>'
	ELSE
		PRINT '<<< ALTERED LOGIN FOR USER Prg_FWP >>>'
END
GO
IF NOT EXISTS(SELECT [name] FROM [master].[sys].[database_principals] WHERE [type] = N'S' AND [name] = N'Admin01')
BEGIN
	CREATE USER [Admin01] FOR LOGIN [Admin01]
	IF @@ERROR <> 0
		PRINT '<<< FAILED CREATING USER FOR LOGIN Admin01 ON MASTER >>>'
	ELSE
		PRINT '<<< CREATED USER FOR LOGIN Admin01 ON MASTER >>>'
END
ELSE
BEGIN
	ALTER USER [Admin01] WITH LOGIN = [Admin01]
	IF @@ERROR <> 0
		PRINT '<<< FAILED ALTER LOGIN FOR USER Admin01 ON MASTER >>>'
	ELSE
		PRINT '<<< ALTERED LOGIN FOR USER Admin01 ON MASTER >>>'
END

-- use new database
USE [SalesWP]
GO

-- Creating DB Users
CREATE USER [Prg_FWP] FOR LOGIN [Prg_FWP] WITH DEFAULT_SCHEMA = [dbo]
IF @@ERROR <> 0
	PRINT '<<< FAILED CREATING USER FOR LOGIN Prg_FWP ON SalesWP >>>'
ELSE
	PRINT '<<< CREATED USER FOR LOGIN Prg_FWP ON SalesWP >>>'
GO
CREATE USER [Admin01] FOR LOGIN [Admin01]
IF @@ERROR <> 0
	PRINT '<<< FAILED CREATING USER FOR LOGIN Admin01 ON SalesWP >>>'
ELSE
	PRINT '<<< CREATED USER FOR LOGIN Admin01 ON SalesWP >>>'
GO

-- Creating Roles
CREATE ROLE [dbadmins] AUTHORIZATION [Admin01]
IF @@ERROR <> 0
	PRINT '<<< FAILED CREATING ROLE dbadmins ON SalesWP >>>'
ELSE
	PRINT '<<< CREATED ROLE dbadmins ON SalesWP >>>'
GO
-- Creating Schemas
---- Main database Schema
CREATE SCHEMA [prog] AUTHORIZATION [dbadmins]
GO
IF NOT EXISTS(SELECT [name] FROM [SalesWP].[sys].[schemas] WHERE [name] = 'prog')
	PRINT '<<< FAILED CREATING SCHEMA prog ON SalesWP >>>'
ELSE
	PRINT '<<< CREATED SCHEMA prog ON SalesWP >>>'
GO
-- Change default schema for Admin01
ALTER USER [Admin01] WITH DEFAULT_SCHEMA = [prog]
IF @@ERROR <> 0
	PRINT '<<< FAILED TO SET DEFAULT SCHEMA prog FOR USER Admin01 ON SalesWP >>>'
ELSE
	PRINT '<<< ALTERED USER Admin01 ON SalesWP SET DEFAULT SCHEMA TO prog >>>'
GO
-- Add Admin01 to dbadmins
EXEC sp_addrolemember 'dbadmins', 'Admin01'
IF @@ERROR <> 0
	PRINT '<<< FAILED ADDING USER Admin01 TO ROLE dbadmins ON SalesWP>>>'
ELSE
	PRINT '<<< ADDED USER Admin01 TO ROLE dbadmins ON SalesWP>>>'
GO
-- GRANT PERMISSIONS
GRANT CREATE TABLE, CREATE PROCEDURE, CREATE FUNCTION, CREATE VIEW ON DATABASE::[SalesWP] TO [Admin01]
IF @@ERROR <> 0
	PRINT '<<< FAILED GRANTING ALL FOR Admin01 TO SalesWP >>>'
ELSE
	PRINT '<<< GRANTED ALL FOR Admin01 TO SalesWP >>>'